# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            http_basic: ~
            provider: db_provider
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }