# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
    #TODO: http://symfony.com/doc/current/security/password_encoding.html

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout: true
            anonymous: true
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: /new, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: /delete, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/tag/new, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/collection, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/personaltag, role: IS_AUTHENTICATED_REMEMBERED }

        - { path: ^/admin/, role: ROLE_ADMIN }